services:
  client:
    image: phonebook-frontend
    build:
      context: ./phonebook-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./phonebook-frontend:/usr/src/app
    environment:
      - VITE_BACKEND_URL=/api
    container_name: phonebook-frontend

  server:
    image: phonebook-backend
    build:
      context: ./phonebook-backend
      dockerfile: dev.Dockerfile
    env_file:
      - ./phonebook-backend/.env # Loads the MONGO_URI
    volumes:
      - ./phonebook-backend:/usr/src/app
    container_name: phonebook-backend
  
  nginx:
    image: nginx:1.20.1
    ports:
      - 8080:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    container_name: phonebook-reverse-proxy
    depends_on:
      - client # Wait for the frontend container to be started
      - server